import './header.css';
import './homePage.css';
import './formPage.css';
import './projectPage.css';
import './tailwinds.css'
import './searchPage.css';
import './banner.css'
import 'swiper/swiper.scss';
import 'swiper/modules/navigation/navigation.scss';
import 'swiper/modules/pagination/pagination.scss';
import 'swiper/modules/scrollbar/scrollbar.scss';
import 'swiper/modules/autoplay/autoplay.scss';